[build]
  publish = "site"
  command = "pip install -r docs-requirements.txt && mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.9"

# Redirect rules
[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/README"
  to = "/"
  status = 301

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Plugin configuration (for when available)
[context.production.environment]
  MKDOCS_STRICT = "true"

[context.deploy-preview.environment]
  MKDOCS_STRICT = "false"